services:
  app:
    build:
      context: .
    container_name: memoir-app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: memoir-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: memoir
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db_data:
